### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by CodeAnthem** [dmzoneill/lidarr-youtube-downloader#3]
Hello, how can I use your app with docker-compose?

**Comment by dmzoneill** [comment]
the docker file is in the repo.

**Comment by jjoshm** [comment]
you can also pass a git url to the `build` of the compose file and it will build from there. 

```
  lidarr-youtube-downloader:
    build: https://github.com/dmzoneill/lidarr-youtube-downloader.git
    volumes:
      - /data:/data
    environment:
      - LIDARR_URL=http://lidarr:8686
      - LIDARR_API_KEY=XXXXXX
      - LIDARR_MUSIC_PATH=/data/media/music
```

You can also pin it to a tag or branch like this `https://github.com/mycompany/example.git#branch_or_tag`

**Comment by dmzoneill** [comment]
Hello! Thank you for the question. While the project currently only has documentation for `docker run`, you can absolutely use docker-compose with this app.

Here's an example docker-compose.yml you can use:

```yaml
version: '3.8'

services:
  lidarr-youtube-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    image: lyd:latest
    container_name: lidarr-youtube-downloader
    environment:
      - LIDARR_URL=http://lidarr:8686
      - LIDARR_API_KEY=your-api-key-here
      - LIDARR_DB=/config/lidarr.db
      - LIDARR_MUSIC_PATH=/music
      # Optional settings
      - MATCH_THRESHOLD=0.8
      - BLACKLIST_KEYWORDS=live,karaoke,cover
    volumes:
      - /path/to/music:/music
      - /path/to/lidarr/db:/config
    depends_on:
      - lidarr
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /path/to/lidarr/config:/config
      - /path/to/music:/music
    restart: unless-stopped
```

**Key points:**
- Replace `/path/to/music` with your actual music directory path
- Replace `/path/to/lidarr/db` with the path to your lidarr.db file
- Replace `/path/to/lidarr/config` with your Lidarr config directory
- Make sure the music paths are consistent between both services
- The `depends_on` ensures Lidarr starts before the downloader attempts to connect

You can run it with:
```bash
docker-compose up --build
```

If you'd like, I can help you create a proper `docker-compose.yml` file in the repository with additional variations (e.g., if you're using an external Lidarr instance). Would that be helpful?
